services:
  - type: web
    name: medicheck-system
    runtime: node
    buildCommand: pnpm install --include=dev && pnpm run build && node dist/scripts/initDb.js
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        sync: false
      - key: CORS_ORIGIN
        sync: false
